services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
      args:
        BASE_HREF: /Documentacion26/
    container_name: siarchivodigital-frontend
    ports:
      - "8078:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: siarchivodigital-backend
    ports:
      - "3040:3060"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always
